//
//  ViewController.swift
//  Li_Yuing_ISU
//
//  Created by Period One on 2018-01-11.
//  Copyright © 2018 Period One. All rights reserved.
//

import UIKit

class ViewController: UIViewController, UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate {

    @IBOutlet weak var tabel: UITableView!
    @IBOutlet weak var searchBar: UISearchBar!
    
    var wordArray = [wordAndMeaning]()
    
    var currentWordArray=[wordAndMeaning]()
    override func viewDidLoad() {
        super.viewDidLoad()
        setUpWords()
        setUpSearchBar()
        alterLayout()
    }
    
    
    private func setUpWords() {
        wordArray.append(wordAndMeaning(word:"abandon", meaning:  "cease to support or look after (someone); desert"))
        wordArray.append(wordAndMeaning(word:"critical", meaning:"expressing adverse or disapproving comments or judgments"))
         wordArray.append(wordAndMeaning(word:"function", meaning: "practical use or purpose in design"))
         wordArray.append(wordAndMeaning(word:"nurture", meaning: "care for and encourage the growth or development of"))
         wordArray.append(wordAndMeaning(word:"limitation", meaning: "a limiting rule or circumstance; a restriction"))
         wordArray.append(wordAndMeaning(word:"approach", meaning: "come near or nearer to (someone or something) in distance"))
        wordArray.append(wordAndMeaning(word:"expertise", meaning:  "expert skill or knowledge in a particular field"))
        wordArray.append(wordAndMeaning(word:"remote", meaning:  "(of a place) situated far from the main centers of population; distant"))
        wordArray.append(wordAndMeaning(word:"various", meaning:  "different from one another; of different kinds or sorts"))
        wordArray.append(wordAndMeaning(word:"harness", meaning:  "control and make use of (natural resources), especially to produce energy"))
        wordArray.append(wordAndMeaning(word:"potential", meaning:  "having or showing the capacity to become or develop into something in the future"))
        wordArray.append(wordAndMeaning(word:"neglect", meaning:  "fail to care for properly"))
        wordArray.append(wordAndMeaning(word:"subjective", meaning:  "based on or influenced by personal feelings, tastes, or opinions"))
        wordArray.append(wordAndMeaning(word:"foundation", meaning:  "the lowest load-bearing part of a building, typically below ground level"))
        wordArray.append(wordAndMeaning(word:"bridge", meaning:  "a structure carrying a road, path, railroad, or canal across a river, ravine, road, railroad, or other obstacle"))
        wordArray.append(wordAndMeaning(word:"meltdown", meaning:  "a disastrous event, especially a rapid fall in share prices"))
        wordArray.append(wordAndMeaning(word:"reiterate", meaning:  "say something again or a number of times, typically for emphasis or clarity"))
        wordArray.append(wordAndMeaning(word:"explore", meaning:  "travel in or through (an unfamiliar country or area) in order to learn about or familiarize oneself with it"))
        wordArray.append(wordAndMeaning(word:"option", meaning:  "a thing that is or may be chosen"))
        wordArray.append(wordAndMeaning(word:"curiosity", meaning:  "a strong desire to know or learn something"))
        wordArray.append(wordAndMeaning(word:"mature", meaning:  "fully developed physically; full-grown"))
        wordArray.append(wordAndMeaning(word:"appreciate", meaning:  "recognize the full worth of"))
        wordArray.append(wordAndMeaning(word:"impressionable", meaning:  "easily influenced because of a lack of critical ability"))
        wordArray.append(wordAndMeaning(word:"appealing", meaning:  "attractive or interesting"))
        wordArray.append(wordAndMeaning(word:"prescription", meaning:  "an instruction written by a medical practitioner that authorizes a patient to be provided a medicine or treatment"))
        wordArray.append(wordAndMeaning(word:"universal", meaning:  "of, affecting, or done by all people or things in the world or in a particular group; applicable to all cases"))
        wordArray.append(wordAndMeaning(word:"affortable", meaning:  "inexpensive; reasonably priced"))
        wordArray.append(wordAndMeaning(word:"odd", meaning:  "different from what is usual or expected; strange"))
        wordArray.append(wordAndMeaning(word:"struggle", meaning:  "make forceful or violent efforts to get free of restraint or constriction"))
        wordArray.append(wordAndMeaning(word:"analysis", meaning:  "detailed examination of the elements or structure of something, typically as a basis for discussion or interpretation"))
        wordArray.append(wordAndMeaning(word:"dilemma", meaning:  "a difficult situation or problem"))
        wordArray.append(wordAndMeaning(word:"strategy", meaning:  "a plan of action or policy designed to achieve a major or overall aim"))
        wordArray.append(wordAndMeaning(word:"infrastructure", meaning:  "the basic physical and organizational structures and facilities (e.g., buildings, roads, and power supplies) needed for the operation of a society or enterprise"))
        wordArray.append(wordAndMeaning(word:"mindset", meaning:  "the established set of attitudes held by someone"))
        wordArray.append(wordAndMeaning(word:"compromise", meaning:  "an agreement or a settlement of a dispute that is reached by each side making concessions"))
        wordArray.append(wordAndMeaning(word:"paradox", meaning:  "a seemingly absurd or self-contradictory statement or proposition that when investigated or explained may prove to be well founded or true"))
        wordArray.append(wordAndMeaning(word:"synergy", meaning:  "the interaction or cooperation of two or more organizations, substances, or other agents to produce a combined effect greater than the sum of their separate effects"))
        wordArray.append(wordAndMeaning(word:"inequality", meaning:  "difference in size, degree, circumstances, etc.; lack of equality"))
        wordArray.append(wordAndMeaning(word:"hierarchy", meaning:  "a system or organization in which people or groups are ranked one above the other according to status or authority"))
        wordArray.append(wordAndMeaning(word:"democracy", meaning:  "a system of government by the whole population or all the eligible members of a state, typically through elected representatives"))
        wordArray.append(wordAndMeaning(word:"collaborate", meaning:  "work jointly on an activity, especially to produce or create something"))
        wordArray.append(wordAndMeaning(word:"manipulate", meaning:  "handle or control (a tool, mechanism, etc.), typically in a skillful manner"))
        wordArray.append(wordAndMeaning(word:"optimise", meaning:  "make the best or most effective use of (a situation, opportunity, or resource)"))
        wordArray.append(wordAndMeaning(word:"withstand", meaning:  "remain undamaged or unaffected by; resist"))
        wordArray.append(wordAndMeaning(word:"compensate", meaning:  "give (someone) something, typically money, in recognition of loss, suffering, or injury incurred; recompense"))
        wordArray.append(wordAndMeaning(word:"undermine", meaning:  "erode the base or foundation of (a rock formation)"))
        wordArray.append(wordAndMeaning(word:"jeopardise", meaning:  "put (someone or something) into a situation in which there is a danger of loss, harm, or failure"))
        wordArray.append(wordAndMeaning(word:"deteriorate", meaning:  "become progressively worse"))
        wordArray.append(wordAndMeaning(word:"impede", meaning:  "delay or prevent (someone or something) by obstructing them; hinder"))
        wordArray.append(wordAndMeaning(word:"exaggerate", meaning:  "represent (something) as being larger, greater, better, or worse than it really is"))
        wordArray.append(wordAndMeaning(word:"prosperous", meaning:  "successful in material terms; flourishing financially"))
        wordArray.append(wordAndMeaning(word:"sustainable", meaning:  "able to be maintained at a certain rate or level"))
        wordArray.append(wordAndMeaning(word:"optimistic", meaning:  "hopeful and confident about the future"))
        wordArray.append(wordAndMeaning(word:"inevitable", meaning:  "certain to happen; unavoidable"))
        wordArray.append(wordAndMeaning(word:"plausible", meaning:  "(of an argument or statement) seeming reasonable or probable"))
        wordArray.append(wordAndMeaning(word:"detrimental", meaning:  "tending to cause harm"))
        wordArray.append(wordAndMeaning(word:"demanding", meaning:  "(of a task) requiring much skill or effort"))
        wordArray.append(wordAndMeaning(word:"overwhelming", meaning:  "(especially of an emotion) very strong"))
        wordArray.append(wordAndMeaning(word:"harbour", meaning:  "a place on the coast where vessels may find shelter, especially one protected from rough water by piers, jetties, and other artificial structures"))
        wordArray.append(wordAndMeaning(word:"pool", meaning:  "a small area of still water, typically one formed naturally"))
        wordArray.append(wordAndMeaning(word:"mirror", meaning:  "a reflective surface, now typically of glass coated with a metal amalgam, that reflects a clear image"))
        wordArray.append(wordAndMeaning(word:"mask", meaning:  "a covering for all or part of the face, worn as a disguise, or to amuse or terrify other people"))
        wordArray.append(wordAndMeaning(word:"hinge", meaning:  "a movable joint or mechanism on which a door, gate, or lid swings as it opens and closes, or that connects linked objects"))
        wordArray.append(wordAndMeaning(word:"shape", meaning:  "the external form or appearance characteristic of someone or something; the outline of an area or figure"))
        wordArray.append(wordAndMeaning(word:"tailor", meaning:  "a person whose occupation is making fitted clothes such as suits, pants, and jackets to fit individual customers"))
        wordArray.append(wordAndMeaning(word:"curb", meaning:  "restrain or keep in check"))
        wordArray.append(wordAndMeaning(word:"vice versa", meaning:  "with the main items in the preceding statement the other way around"))
        wordArray.append(wordAndMeaning(word:"per se", meaning:  "by or in itself or themselves; intrinsically"))
        wordArray.append(wordAndMeaning(word:"de facto", meaning:  "in fact, or in effect, whether by right or not"))
        wordArray.append(wordAndMeaning(word:"status quo", meaning:  "the existing state of affairs, especially regarding social or political issues"))
        wordArray.append(wordAndMeaning(word:"per capita", meaning:  "for each person; in relation to people taken individually"))
        wordArray.append(wordAndMeaning(word:"theoretical", meaning:  "concerned with or involving the theory of a subject or area of study rather than its practical application"))
        wordArray.append(wordAndMeaning(word:"practical", meaning:  "of or concerned with the actual doing or use of something rather than with theory and ideas"))
        wordArray.append(wordAndMeaning(word:"physical", meaning:  "relating to the body as opposed to the mind"))
        wordArray.append(wordAndMeaning(word:"intelligence", meaning:  "the ability to acquire and apply knowledge and skills"))
        wordArray.append(wordAndMeaning(word:"motivate", meaning:  "provide (someone) with a motive for doing something"))
         wordArray.append(wordAndMeaning(word:"quality", meaning:  "be entitled to a particular benefit or privilege by fulfilling a necessary condition"))
         wordArray.append(wordAndMeaning(word:"talent", meaning:  "natural aptitude or skill"))
         wordArray.append(wordAndMeaning(word:"course", meaning:  "the route or direction followed by a ship, aircraft, road, or river"))
         wordArray.append(wordAndMeaning(word:"discipline", meaning:  "the practice of training people to obey rules or a code of behavior, using punishment to correct disobedience"))
         wordArray.append(wordAndMeaning(word:"subject", meaning:  "a person or thing that is being discussed, described, or dealt with"))
         wordArray.append(wordAndMeaning(word:"adolescent", meaning:  "(of a young person) in the process of developing from a child into an adult"))
         wordArray.append(wordAndMeaning(word:"interactive", meaning:  "(of two people or things) influencing or having an effect on each other"))
         wordArray.append(wordAndMeaning(word:"feedback", meaning:  "information about reactions to a product, a person's performance of a task, etc., used as a basis for improvement"))
         wordArray.append(wordAndMeaning(word:"ecosystem", meaning:  "a biological community of interacting organisms and their physical environment"))
         wordArray.append(wordAndMeaning(word:"preserve", meaning:  "maintain (something) in its original or existing state"))
         wordArray.append(wordAndMeaning(word:"discharge", meaning:  "allow (a liquid, gas, or other substance) to flow out from where it has been confined"))
         wordArray.append(wordAndMeaning(word:"contaminate", meaning:  "make (something) impure by exposure to or addition of a poisonous or polluting substance"))
         wordArray.append(wordAndMeaning(word:"degrade", meaning:  "treat or regard (someone) with contempt or disrespect"))
         wordArray.append(wordAndMeaning(word:"shortage", meaning:  "a state or situation in which something needed cannot be obtained in sufficient amounts"))
         wordArray.append(wordAndMeaning(word:"lack", meaning:  "the state of being without or not having enough of something"))
         wordArray.append(wordAndMeaning(word:"deficiency", meaning:  "a failing or shortcoming"))
         wordArray.append(wordAndMeaning(word:"convenient", meaning:  "fitting in well with a person's needs, activities, and plans"))
         wordArray.append(wordAndMeaning(word:"productivity", meaning:  "the state or quality of producing something, especially crops"))
         wordArray.append(wordAndMeaning(word:"digital", meaning:  "(of signals or data) expressed as series of the digits 0 and 1, typically represented by values of a physical quantity such as voltage or magnetic polarization"))
         wordArray.append(wordAndMeaning(word:"electronic", meaning:  "(of a device) having or operating with the aid of many small components, especially microchips and transistors, that control and direct an electric current"))
         wordArray.append(wordAndMeaning(word:"virtual", meaning:  "almost or nearly as described, but not completely or according to strict definition"))
         wordArray.append(wordAndMeaning(word:"infringe", meaning:  "actively break the terms of (a law, agreement, etc.)"))
         wordArray.append(wordAndMeaning(word:"pirate", meaning:  "a person who attacks and robs ships at sea"))
         wordArray.append(wordAndMeaning(word:"security", meaning:  "the state of being free from danger or threat"))
         wordArray.append(wordAndMeaning(word:"radiation", meaning:  "he emission of energy as electromagnetic waves or as moving subatomic particles, especially high-energy particles that cause ionization"))
         wordArray.append(wordAndMeaning(word:"innovation", meaning:  "a new method, idea, product, etc"))
         wordArray.append(wordAndMeaning(word:"invention", meaning:  "the action of inventing something, typically a process or device"))
         wordArray.append(wordAndMeaning(word:"hacker", meaning:  "a person who uses computers to gain unauthorized access to data"))
         wordArray.append(wordAndMeaning(word:"netizen", meaning:  "user of the Internet, especially a habitual or avid one"))
         wordArray.append(wordAndMeaning(word:"blog", meaning:  "a regularly updated website or web page, typically one run by an individual or small group, that is written in an informal or conversational style"))
         wordArray.append(wordAndMeaning(word:"cybercrime", meaning:  "criminal activities carried out by means of computers or the Internet"))
         wordArray.append(wordAndMeaning(word:"offensive", meaning:  "causing someone to feel deeply hurt, upset, or angry"))
         wordArray.append(wordAndMeaning(word:"violence", meaning:  "behavior involving physical force intended to hurt, damage, or kill someone or something"))
         wordArray.append(wordAndMeaning(word:"legal", meaning:  "of, based on, or concerned with the law"))
         wordArray.append(wordAndMeaning(word:"gamble", meaning:  "play games of chance for money; bet"))
         wordArray.append(wordAndMeaning(word:"telecommunication", meaning:  "communication over a distance by cable, telegraph, telephone, or broadcasting"))
        wordArray.append(wordAndMeaning(word:"popularity", meaning:  "the state or condition of being liked, admired, or supported by many people"))
        wordArray.append(wordAndMeaning(word:"poverty", meaning:  "the state of being extremely poor"))
        wordArray.append(wordAndMeaning(word:"budget", meaning:  "an estimate of income and expenditure for a set period of time"))
        wordArray.append(wordAndMeaning(word:"authority", meaning:  "the power or right to give orders, make decisions, and enforce obedience"))
        wordArray.append(wordAndMeaning(word:"implement", meaning:  "a tool, utensil, or other piece of equipment, especially as used for a particular purpose"))
        wordArray.append(wordAndMeaning(word:"supervise", meaning:  "observe and direct the execution of (a task, project, or activity)"))
        wordArray.append(wordAndMeaning(word:"military", meaning:  "relating to or characteristic of soldiers or armed forces"))
        wordArray.append(wordAndMeaning(word:"policy", meaning:  "a course or principle of action adopted or proposed by a government, party, business, or individual"))
        wordArray.append(wordAndMeaning(word:"obligation", meaning:  "an act or course of action to which a person is morally or legally bound; a duty or commitment"))
        wordArray.append(wordAndMeaning(word:"investment", meaning:  "the action or process of investing money for profit or material result"))
        wordArray.append(wordAndMeaning(word:"prioritise", meaning:  "designate or treat (something) as more important than other things"))
        wordArray.append(wordAndMeaning(word:"enact", meaning:  "make (a bill or other proposal) law"))
        wordArray.append(wordAndMeaning(word:"service", meaning:  "the action of helping or doing work for someone"))
        wordArray.append(wordAndMeaning(word:"transportation", meaning:  "the action of transporting someone or something or the process of being transported"))
        wordArray.append(wordAndMeaning(word:"combat", meaning:  "fighting between armed forces"))
        wordArray.append(wordAndMeaning(word:"corruption", meaning:  "dishonest or fraudulent conduct by those in power, typically involving bribery"))
        wordArray.append(wordAndMeaning(word:"ensure", meaning:  "make certain that (something) shall occur or be the case"))
        wordArray.append(wordAndMeaning(word:"gap", meaning:  "a break or hole in an object or between two objects"))
        wordArray.append(wordAndMeaning(word:"create", meaning:  "bring (something) into existence"))
        wordArray.append(wordAndMeaning(word:"silver", meaning:  "a precious shiny grayish-white metal, the chemical element of atomic number 47"))
        wordArray.append(wordAndMeaning(word:"twilight", meaning:  "the soft glowing light from the sky when the sun is below the horizon, caused by the refraction and scattering of the sun's rays from the atmosphere"))
        wordArray.append(wordAndMeaning(word:"senior", meaning:  "of a more advanced age"))
        wordArray.append(wordAndMeaning(word:"demographics", meaning:  "statistical data relating to the population and particular groups within it"))
        wordArray.append(wordAndMeaning(word:"retirement", meaning:  "the action or fact of leaving one's job and ceasing to work"))
        wordArray.append(wordAndMeaning(word:"pension", meaning:  "a regular payment made during a person's retirement from an investment fund to which that person or their employer has contributed during their working life"))
        wordArray.append(wordAndMeaning(word:"volunteer", meaning:  "a person who freely offers to take part in an enterprise or undertake a task"))
        wordArray.append(wordAndMeaning(word:"expert", meaning:  "a person who has a comprehensive and authoritative knowledge of or skill in a particular area"))
        wordArray.append(wordAndMeaning(word:"vulnerable", meaning:  "susceptible to physical or emotional attack or harm"))
        wordArray.append(wordAndMeaning(word:"addictive", meaning:  "(of a substance, thing, or activity) causing or likely to cause someone to become addicted to it"))
        wordArray.append(wordAndMeaning(word:"imitate", meaning:  "take or follow as a model"))
        wordArray.append(wordAndMeaning(word:"naughty", meaning:  "(especially of children) disobedient; badly behaved"))
        wordArray.append(wordAndMeaning(word:"gender", meaning:  "the state of being male or female (typically used with reference to social and cultural differences rather than biological ones)"))
        wordArray.append(wordAndMeaning(word:"discrimination", meaning:  "the unjust or prejudicial treatment of different categories of people or things, especially on the grounds of race, age, or sex"))
        wordArray.append(wordAndMeaning(word:"discrimination", meaning:  "the unjust or prejudicial treatment of different categories of people or things, especially on the grounds of race, age, or sex"))
         wordArray.append(wordAndMeaning(word:"patient", meaning:  "able to accept or tolerate delays, problems, or suffering without becoming annoyed or anxious"))
        wordArray.append(wordAndMeaning(word:"aggressive", meaning:  "ready or likely to attack or confront; characterized by or resulting from aggression"))
        wordArray.append(wordAndMeaning(word:"gossip", meaning:  "casual or unconstrained conversation or reports about other people, typically involving details that are not confirmed as being true"))
        wordArray.append(wordAndMeaning(word:"pregnant", meaning:  "(of a woman or female animal) having a child or young developing in the uterus"))
        wordArray.append(wordAndMeaning(word:"rear", meaning:  "the back part of something, especially a building or vehicle"))
        wordArray.append(wordAndMeaning(word:"workaholic", meaning:  "a person who compulsively works hard and long hours"))
        wordArray.append(wordAndMeaning(word:"intense", meaning:  "of extreme force, degree, or strength"))
        wordArray.append(wordAndMeaning(word:"fierce", meaning:  "having or displaying an intense or ferocious aggressiveness"))
        wordArray.append(wordAndMeaning(word:"competition", meaning:  "the activity or condition of competing"))
        wordArray.append(wordAndMeaning(word:"fatigue", meaning:  "extreme tiredness, typically resulting from mental or physical exertion or illness"))
        wordArray.append(wordAndMeaning(word:"workplace", meaning:  "a place where people work, such as an office or factory"))
        wordArray.append(wordAndMeaning(word:"colleague", meaning:  "a person with whom one works, especially in a profession or business"))
        wordArray.append(wordAndMeaning(word:"rural", meaning:  "in, relating to, or characteristic of the countryside rather than the town"))
        wordArray.append(wordAndMeaning(word:"suburb", meaning:  "an outlying district of a city, especially a residential one"))
        wordArray.append(wordAndMeaning(word:"urbanisation", meaning:  "the process of making an area more urban"))
        wordArray.append(wordAndMeaning(word:"metropolis", meaning:  "the capital or chief city of a country or region"))
        wordArray.append(wordAndMeaning(word:"density", meaning:  "the degree of compactness of a substance"))
        wordArray.append(wordAndMeaning(word:"congestion", meaning:  "the state of being congested"))
        wordArray.append(wordAndMeaning(word:"press", meaning:  "move or cause to move into a position of contact with something by exerting continuous physical force"))
        wordArray.append(wordAndMeaning(word:"coverage", meaning:  "the extent to which something deals with or applies to something else"))
        wordArray.append(wordAndMeaning(word:"fair", meaning:  "in accordance with the rules or standards; legitimate"))
        wordArray.append(wordAndMeaning(word:"cater", meaning:  "provide food and drink, typically at social events and in a professional capacity"))
        wordArray.append(wordAndMeaning(word:"hook", meaning:  "a piece of metal or other material, curved or bent back at an angle, for catching hold of or hanging things on"))
        wordArray.append(wordAndMeaning(word:"unveil", meaning:  "remove a veil or covering from, especially uncover (a new monument or work of art) as part of a public ceremony"))
        wordArray.append(wordAndMeaning(word:"mislead", meaning:  "cause (someone) to have a wrong idea or impression about someone or something"))
        wordArray.append(wordAndMeaning(word:"opinion", meaning:  "a view or judgment formed about something, not necessarily based on fact or knowledge"))
        wordArray.append(wordAndMeaning(word:"commercial", meaning:  "concerned with or engaged in commerce"))
        wordArray.append(wordAndMeaning(word:"promotion", meaning:  "activity that supports or provides active encouragement for the furtherance of a cause, venture, or aim"))
        wordArray.append(wordAndMeaning(word:"target", meaning:  "a person, object, or place selected as the aim of an attack"))
        wordArray.append(wordAndMeaning(word:"shopaholic", meaning:  "a compulsive shopper"))
        wordArray.append(wordAndMeaning(word:"induce", meaning:  "succeed in persuading or influencing (someone) to do something"))
        wordArray.append(wordAndMeaning(word:"stimulate", meaning:  "raise levels of physiological or nervous activity in (the body or any biological system)"))
        wordArray.append(wordAndMeaning(word:"purchase", meaning:  "acquire (something) by paying for it; buy"))
        wordArray.append(wordAndMeaning(word:"criminal", meaning:  "a person who has committed a crime"))
        wordArray.append(wordAndMeaning(word:"offender", meaning:  "a person who commits an illegal act"))
        wordArray.append(wordAndMeaning(word:"innocent", meaning:  "not guilty of a crime or offense"))
        wordArray.append(wordAndMeaning(word:"punish", meaning:  "inflict a penalty or sanction on (someone) as retribution for an offense, especially a transgression of a legal or moral code"))
        wordArray.append(wordAndMeaning(word:"jail", meaning:  "a place for the confinement of people accused or convicted of a crime"))
        wordArray.append(wordAndMeaning(word:"commit", meaning:  "carry out or perpetrate (a mistake, crime, or immoral act)"))
        wordArray.append(wordAndMeaning(word:"juvenile", meaning:  "of, for, or relating to young people"))
        wordArray.append(wordAndMeaning(word:"threat", meaning:  "a statement of an intention to inflict pain, injury, damage, or other hostile action on someone in retribution for something done or not done"))
        wordArray.append(wordAndMeaning(word:"preventive", meaning:  "designed to keep something undesirable such as illness, harm, or accidents from occurring"))
        wordArray.append(wordAndMeaning(word:"deterrent", meaning:  "a thing that discourages or is intended to discourage someone from doing something"))
        wordArray.append(wordAndMeaning(word:"fad", meaning:  "an intense and widely shared enthusiasm for something, especially one that is short-lived and without basis in the object's qualities; a craze"))
        wordArray.append(wordAndMeaning(word:"gorgeous", meaning:  "beautiful; very attractive"))
        wordArray.append(wordAndMeaning(word:"parade", meaning:  "a public procession, especially one celebrating a special day or event and including marching bands and floats"))
        wordArray.append(wordAndMeaning(word:"celebrity", meaning:  "a famous person"))
        wordArray.append(wordAndMeaning(word:"confident", meaning:  "feeling or showing confidence in oneself; self-assured"))
        wordArray.append(wordAndMeaning(word:"superficial", meaning:  "existing or occurring at or on the surface"))
        wordArray.append(wordAndMeaning(word:"diversity", meaning:  "the state of being diverse; variety"))
        wordArray.append(wordAndMeaning(word:"nutritious", meaning:  "nourishing; efficient as food"))
        wordArray.append(wordAndMeaning(word:"recipe", meaning:  "a set of instructions for preparing a particular dish, including a list of the ingredients required"))
        wordArray.append(wordAndMeaning(word:"architecture", meaning:  "the art or practice of designing and constructing buildings"))
        wordArray.append(wordAndMeaning(word:"esthetics", meaning:  "a set of principles underlying and guiding the work of a particular artist or artistic movement"))
        wordArray.append(wordAndMeaning(word:"applicant", meaning:  "a person who makes a formal application for something, typically a job"))
        wordArray.append(wordAndMeaning(word:"aviation", meaning:  "the flying or operating of aircraft"))
        wordArray.append(wordAndMeaning(word:"blast", meaning:  "to explode or destroy something or someone with explosives, or to break through or hit something with a similar, very strong force"))
        wordArray.append(wordAndMeaning(word:"bounce", meaning:  "to (cause to) move up or away after hitting a surface"))
        wordArray.append(wordAndMeaning(word:"bound", meaning:  "certain or extremely likely to happen"))
        wordArray.append(wordAndMeaning(word:"casualty", meaning:  "a person injured or killed in a serious accident or war"))
        wordArray.append(wordAndMeaning(word:"confine", meaning:  "to limit an activity, person, or problem in some way"))
        wordArray.append(wordAndMeaning(word:"dawn", meaning:  "the period in the day when light from the sun begins to appear in the sky"))
        wordArray.append(wordAndMeaning(word:"determination", meaning:  "the ability to continue trying to do something, although it is very difficult"))
        wordArray.append(wordAndMeaning(word:"evaporate", meaning:  "to cause a liquid to change to a gas, especially by heating"))
        wordArray.append(wordAndMeaning(word:"fraction", meaning:  "a number that results from dividing one whole number by another"))
        wordArray.append(wordAndMeaning(word:"frustrate", meaning:  "to make someone feel annoyed or less confident because they cannot achieve what they want"))
        wordArray.append(wordAndMeaning(word:"grim", meaning:  "worrying, without hope"))
        wordArray.append(wordAndMeaning(word:"herd", meaning:  "a large group of animals of the same type that live and feed together"))
        wordArray.append(wordAndMeaning(word:"mission", meaning:  "an important job, especially a military one, that someone is sent somewhere to do"))
        wordArray.append(wordAndMeaning(word:"molecule", meaning:  "the simplest unit of a chemical substance, usually a group of two or more atoms"))
        wordArray.append(wordAndMeaning(word:"orderly", meaning:  "a hospital worker who does jobs for which no training is necessary, such as helping the nurses or carrying heavy things"))
        wordArray.append(wordAndMeaning(word:"prevalent", meaning:  "existing very commonly or happening often"))
        wordArray.append(wordAndMeaning(word:"revelation", meaning:  "the act of making something known that was secret, or a fact that is made known"))
        wordArray.append(wordAndMeaning(word:"committee", meaning:  "a small group of people chosen to represent a larger organization and either make decisions or collect information for it"))
        wordArray.append(wordAndMeaning(word:"factor", meaning:  "a fact or situation that influences the result of something"))
        wordArray.append(wordAndMeaning(word:"shock", meaning:  "(the emotional or physical reaction to) a sudden, unexpected, and usually unpleasant event or experience"))
        wordArray.append(wordAndMeaning(word:"port", meaning:  "a town by the sea or by a river that has a harbour, or the harbour itself"))
        wordArray.append(wordAndMeaning(word:"arise", meaning:  "formal to happen"))
        wordArray.append(wordAndMeaning(word:"prospect", meaning:  "the possibility that something good might happen in the future"))
        wordArray.append(wordAndMeaning(word:"throat", meaning:  "the front of the neck, or the space inside the neck down which food and air can go"))
        wordArray.append(wordAndMeaning(word:"pin", meaning:  "a small thin piece of metal with a point at one end, especially used for temporarily holding pieces of cloth together"))
        wordArray.append(wordAndMeaning(word:"possession", meaning:  "the fact that you have or own something"))
        wordArray.append(wordAndMeaning(word:"column", meaning:  "one of several vertical blocks of print into which a page of a newspaper or magazine is divided"))
        wordArray.append(wordAndMeaning(word:"structural", meaning:  " relating to the way in which parts of a system or object are arranged"))
        wordArray.append(wordAndMeaning(word:"summit", meaning:  "an important formal meeting between leaders of governments from two or more countries"))
        wordArray.append(wordAndMeaning(word:"platform", meaning:  " a flat raised area or structure"))
        wordArray.append(wordAndMeaning(word:"nowhere", meaning:  "in, at, or to no place; not anywhere"))
        wordArray.append(wordAndMeaning(word:"shrug", meaning:  "to raise your shoulders and then lower them in order to say you do not know or are not interested"))
        wordArray.append(wordAndMeaning(word:"plot", meaning:  "the story of a book, film, play, etc"))
        wordArray.append(wordAndMeaning(word:"tide", meaning:  "the rise and fall of the sea that happens twice every day"))
        wordArray.append(wordAndMeaning(word:"loyal", meaning:  "firm and not changing in your friendship with or support for a person or an organization, or in your belief in your principles"))
        wordArray.append(wordAndMeaning(word:"ceremony", meaning:  "formal ceremonial (a set of) formal acts, often fixed and traditional, performed on important social or religious occasions"))
        wordArray.append(wordAndMeaning(word:"splendid", meaning:  "excellent, or beautiful and impressive"))
        wordArray.append(wordAndMeaning(word:"specimen", meaning:  "something shown or examined as an example; a typical example"))
        wordArray.append(wordAndMeaning(word:"prompt", meaning:  "to make something happen"))
        wordArray.append(wordAndMeaning(word:"bother", meaning:  "to make the effort to do something"))
        wordArray.append(wordAndMeaning(word:"transmission", meaning:  "the process of broadcasting something by radio, television, etc., or something that is broadcast"))
        wordArray.append(wordAndMeaning(word:"fade", meaning:  "to (cause to) lose colour, brightness, or strength gradually"))
        wordArray.append(wordAndMeaning(word:"horizon", meaning:  "the line at the farthest place that you can see, where the sky seems to touch the land or sea"))
        wordArray.append(wordAndMeaning(word:"embassy", meaning:  "the group of people who represent their country in a foreign country"))
        wordArray.append(wordAndMeaning(word:"scruity", meaning:  "the careful and detailed examination of something in order to get information about it"))
        wordArray.append(wordAndMeaning(word:"likelihood", meaning:  "the chance that something will happen"))
        wordArray.append(wordAndMeaning(word:"prescribe", meaning:  "(of a doctor) to say what medical treatment someone should have"))
        wordArray.append(wordAndMeaning(word:"exceed", meaning:  "to be greater than a number or amount, or to go past an allowed limit"))
        wordArray.append(wordAndMeaning(word:"prestige", meaning:  "respect and admiration given to someone or something, usually because of a reputation for high quality, success, or social influence"))
        wordArray.append(wordAndMeaning(word:"immigrant", meaning:  "a person who has come to a different country in order to live there permanently"))
        wordArray.append(wordAndMeaning(word:"humble", meaning:  "not proud or not believing that you are important"))
        wordArray.append(wordAndMeaning(word:"purity", meaning:  "the state of not being mixed with anything else"))
        wordArray.append(wordAndMeaning(word:"cement", meaning:  "a grey powder that is mixed with water and sand to make mortar or with water, sand, and small stones to make concrete"))
        wordArray.append(wordAndMeaning(word:"technician", meaning:  "a worker trained with special skills, especially in science or engineering"))
        wordArray.append(wordAndMeaning(word:"launch", meaning:  "an event to celebrate or introduce something new"))
        wordArray.append(wordAndMeaning(word:"concentrate", meaning:  "to direct your attention or your efforts towards a particular activity, subject, or problem"))
        wordArray.append(wordAndMeaning(word:"protein", meaning:  "one of the many substances found in food such as meat, cheese, fish, or eggs, that is necessary for the body to grow and be strong"))
        wordArray.append(wordAndMeaning(word:"convict", meaning:  "to decide officially in a law court that someone is guilty of a crime"))
        wordArray.append(wordAndMeaning(word:"coordinate", meaning:  "to make many different things work effectively as a whole"))
        wordArray.append(wordAndMeaning(word:"leak", meaning:  "(of a liquid or gas) to escape from a hole or crack in a pipe or container; (of a container) to allow liquid or gas to escape"))
        wordArray.append(wordAndMeaning(word:"unconscious", meaning:  "in the state of not being awake, especially as the result of a head injury"))
        wordArray.append(wordAndMeaning(word:"undertake", meaning:  "to do or begin to do something, especially something that will take a long time or be difficult"))
        wordArray.append(wordAndMeaning(word:"isolate", meaning:  "to separate something from other things with which it is connected or mixed"))
        wordArray.append(wordAndMeaning(word:"gross", meaning:  "(in) total"))
        wordArray.append(wordAndMeaning(word:"harsh", meaning:  "unpleasant, unkind, cruel, or more severe than is necessary"))
        wordArray.append(wordAndMeaning(word:"raid", meaning:  "a short sudden attack, usually by a small group of people"))
        wordArray.append(wordAndMeaning(word:"soak", meaning:  "to make something very wet, or (of liquid) to be absorbed in large amounts"))
        wordArray.append(wordAndMeaning(word:"shrink", meaning:  " to become smaller, or to make something smaller"))
        wordArray.append(wordAndMeaning(word:"maximum", meaning:  "being the largest amount or number allowed or possible"))
        wordArray.append(wordAndMeaning(word:"sufficient", meaning:  "enough for a particular purpose"))
        wordArray.append(wordAndMeaning(word:"erect", meaning:  "to build a building, wall, or other structure"))
        wordArray.append(wordAndMeaning(word:"temptation", meaning:  "the wish to do or have something that you know you should not do or have"))
        wordArray.append(wordAndMeaning(word:"spokesman", meaning:  "someone who is chosen by a group or organization to speak officially to the public for them"))
        wordArray.append(wordAndMeaning(word:"gratitude", meaning:  "the feeling or quality of being grateful"))
        wordArray.append(wordAndMeaning(word:"resource", meaning:  "a useful or valuable possession or quality of a country, organization, or person"))
        wordArray.append(wordAndMeaning(word:"proceed", meaning:  "to continue as planned"))
        wordArray.append(wordAndMeaning(word:"democracy", meaning:  "a country in which power is held by elected representatives"))
        wordArray.append(wordAndMeaning(word:"consent", meaning:  "permission or agreement"))
        wordArray.append(wordAndMeaning(word:"sack", meaning:  "a large bag made of strong cloth, paper, or plastic, used to store large amounts of something"))
        wordArray.append(wordAndMeaning(word:"preach", meaning:  "(especially of a priest or minister in a church) to give a religious speech"))
        wordArray.append(wordAndMeaning(word:"plantation", meaning:  "a large farm, especially in a hot part of the world, on which a particular type of crop is grown"))
        wordArray.append(wordAndMeaning(word:"vain", meaning:  "unsuccessful; of no value"))
        wordArray.append(wordAndMeaning(word:"sow", meaning:  "to put seeds in or on the ground so that plants will grow"))
        wordArray.append(wordAndMeaning(word:"notify", meaning:  "to tell someone officially about something"))
        wordArray.append(wordAndMeaning(word:"classify", meaning:  "to divide things into groups according to their type"))
        wordArray.append(wordAndMeaning(word:"trim", meaning:  "to make something tidier or more level by cutting a small amount off it"))
        wordArray.append(wordAndMeaning(word:"hum", meaning:  "to make a continuous low sound"))
        wordArray.append(wordAndMeaning(word:"ban", meaning:  "to forbid (= refuse to allow) something, especially officially"))
        wordArray.append(wordAndMeaning(word:"board", meaning:  "a thin, flat piece of cut wood or other hard material, often used for a particular purpose"))
        wordArray.append(wordAndMeaning(word:"circumstance", meaning:  " a fact or event that makes a situation the way it is"))
        wordArray.append(wordAndMeaning(word:"challenge", meaning:  "(the situation of being faced with) something that needs great mental or physical effort in order "))
        wordArray.append(wordAndMeaning(word:"complex", meaning:  "involving a lot of different but related parts"))
        wordArray.append(wordAndMeaning(word:"omit", meaning:  " to fail to include or do something"))
        wordArray.append(wordAndMeaning(word:"calendar", meaning:  "a printed table showing all the days, weeks, and months of the year"))
        wordArray.append(wordAndMeaning(word:"vanish", meaning:  "to disappear or stop being present or existing, especially in a sudden, surprising way"))
        wordArray.append(wordAndMeaning(word:"bang", meaning:  "to (cause something to) make a sudden very loud noise or noises"))
        wordArray.append(wordAndMeaning(word:"convenience", meaning:  " the state of being convenient"))
        wordArray.append(wordAndMeaning(word:"extreme", meaning:  "very large in amount or degree"))
        wordArray.append(wordAndMeaning(word:"relief", meaning:  "a feeling of happiness that something unpleasant has not happened or has ended"))
        wordArray.append(wordAndMeaning(word:"faith", meaning:  "great trust or confidence in something or someone"))
        wordArray.append(wordAndMeaning(word:"dramatic", meaning:  "very sudden or noticeable, or full of action and excitement"))
        wordArray.append(wordAndMeaning(word:"sensitive", meaning:  "easily upset by the things people say or do, or causing people to be upset, embarrassed, or angry"))
        wordArray.append(wordAndMeaning(word:"abuse", meaning:  "to use something for the wrong purpose in a way that is harmful or morally wrong"))
        wordArray.append(wordAndMeaning(word:"pilot", meaning:  "a person who flies an aircraft"))
        wordArray.append(wordAndMeaning(word:"smooth", meaning:  "having a surface or consisting of a substance that is perfectly regular and has no holes, lumps, or areas that rise or fall suddenly"))
        wordArray.append(wordAndMeaning(word:"architect", meaning:  "a person whose job is to design new buildings and make certain that they are built correctly"))
        wordArray.append(wordAndMeaning(word:"bind", meaning:  "to tie something tightly or to fasten something"))
        wordArray.append(wordAndMeaning(word:"stretch", meaning:  " to cause something to reach, often as far as possible, in a particular direction"))
        wordArray.append(wordAndMeaning(word:"resort", meaning:  "a place where many people go for rest, sport, or another stated purpose"))
        wordArray.append(wordAndMeaning(word:"rescue", meaning:  "to help someone or something out of a dangerous, harmful, or unpleasant situation"))
        wordArray.append(wordAndMeaning(word:"inspire", meaning:  "to make someone feel that they want to do something and can do it"))
        wordArray.append(wordAndMeaning(word:"bulb", meaning:  "a round root of some plants from which the plant grows"))
        wordArray.append(wordAndMeaning(word:"timely", meaning:  "happening at the best possible moment"))
        wordArray.append(wordAndMeaning(word:"pour", meaning:  "to make a substance flow from a container, especially into another container, by raising just one side of the container that the substance is in"))
        wordArray.append(wordAndMeaning(word:"privilege", meaning:  "an advantage that only one person or group of people has, usually because of their position or because they are rich"))
        wordArray.append(wordAndMeaning(word:"amateur", meaning:  "taking part in an activity for pleasure, not as a job"))
        wordArray.append(wordAndMeaning(word:"absorb", meaning:  "to take something in, especially gradually"))
        wordArray.append(wordAndMeaning(word:"crawl", meaning:  "to move slowly or with difficulty, especially with your body stretched out along the ground or on hands and knees"))
        wordArray.append(wordAndMeaning(word:"guideline", meaning:  "information intended to advise people on how something should be done or what something should be"))
        wordArray.append(wordAndMeaning(word:"logic", meaning:  "a particular way of thinking, especially one that is reasonable and based on good judgment"))
        wordArray.append(wordAndMeaning(word:"heave", meaning:  "to move something heavy using a lot of effort"))
        wordArray.append(wordAndMeaning(word:"dynamic", meaning:  "having a lot of ideas and enthusiasm"))
        wordArray.append(wordAndMeaning(word:"fluid", meaning:  "a substance that flows and is not solid"))
        wordArray.append(wordAndMeaning(word:"gesture", meaning:  "a movement of the hands, arms, or head, etc. to express an idea or feeling"))
        wordArray.append(wordAndMeaning(word:"alarm", meaning:  "a warning of danger, usually a loud noise or flashing light"))
        wordArray.append(wordAndMeaning(word:"dial", meaning:  "to operate a phone or make a phone call to someone by choosing a particular series of numbers on the phone"))
        wordArray.append(wordAndMeaning(word:"slice", meaning:  "a flat, often thin, piece of food that has been cut from a larger piece"))
        wordArray.append(wordAndMeaning(word:"vacant", meaning:  "not filled or occupied; available to be used"))
        wordArray.append(wordAndMeaning(word:"spur", meaning:  "to encourage an activity or development or make it happen faster"))
        wordArray.append(wordAndMeaning(word:"wreck", meaning:  "to destroy or badly damage something"))
        wordArray.append(wordAndMeaning(word:"dispose", meaning:  "to make someone feel a particular way towards someone or something"))
        wordArray.append(wordAndMeaning(word:"slap", meaning:  "a quick hit with the flat part of the hand or other flat object"))
        wordArray.append(wordAndMeaning(word:"balcony", meaning:  "an area with a wall or bars around it that is joined to the outside wall of a building on an upper level"))
        wordArray.append(wordAndMeaning(word:"squeeze", meaning:  "to press something firmly, especially from all sides in order to change its shape, reduce its size, or remove liquid from it"))
        wordArray.append(wordAndMeaning(word:"sour", meaning:  "having a sharp, sometimes unpleasant, taste or smell, like a lemon, and not sweet"))
        wordArray.append(wordAndMeaning(word:"exchange", meaning:  "the act of giving something to someone and them giving you something else"))
        wordArray.append(wordAndMeaning(word:"bend", meaning:  " to (cause to) curve"))
        wordArray.append(wordAndMeaning(word:"trail", meaning:  "a path through a countryside, mountain, or forest area, often made or used for a particular purpose"))
        wordArray.append(wordAndMeaning(word:"horrible", meaning:  "very unpleasant or bad"))
        wordArray.append(wordAndMeaning(word:"benefit", meaning:  "a helpful or good effect, or something intended to help"))
        wordArray.append(wordAndMeaning(word:"readily", meaning:  "quickly, immediately, willingly, or without any problem"))
        wordArray.append(wordAndMeaning(word:"alter", meaning:  "to change something, usually slightly, or to cause the characteristics of something to change"))
        wordArray.append(wordAndMeaning(word:"focus", meaning:  "the main or central point of something, especially of attention or interest"))
        wordArray.append(wordAndMeaning(word:"stoop", meaning:  "to bend the top half of the body forward and down"))
        wordArray.append(wordAndMeaning(word:"unify", meaning:  "to bring together; combine"))
        wordArray.append(wordAndMeaning(word:"ambition", meaning:  "a strong wish to achieve something"))
        wordArray.append(wordAndMeaning(word:"attack", meaning:  "to try to hurt or defeat using violence"))
        wordArray.append(wordAndMeaning(word:"harmony", meaning:  "a pleasant musical sound made by different notes being played or sung at the same time"))
        wordArray.append(wordAndMeaning(word:"constant", meaning:  "happening a lot or all the time"))
        wordArray.append(wordAndMeaning(word:"shear", meaning:  "to cut the wool off a sheep"))
        wordArray.append(wordAndMeaning(word:"pause", meaning:  "a short period in which something such as a sound or an activity is stopped before starting again"))
        wordArray.append(wordAndMeaning(word:"hang", meaning:  "to fasten or support something at the top leaving the other parts free to move, or to be held in this way"))
        wordArray.append(wordAndMeaning(word:"reveal", meaning:  "to make known or show something that is surprising or that was previously secret"))
        wordArray.append(wordAndMeaning(word:"wrist", meaning:  "the part of the body between the hand and the arm"))
        wordArray.append(wordAndMeaning(word:"virus", meaning:  "an extremely small piece of organic material that causes disease in humans, animals, and plants"))
        wordArray.append(wordAndMeaning(word:"accent", meaning:  "the way in which people in a particular area, country, or social group pronounce words"))
        wordArray.append(wordAndMeaning(word:"tame", meaning:  "(especially of animals) not wild or dangerous, either naturally or because of training or long involvement with humans"))
        wordArray.append(wordAndMeaning(word:"measure", meaning:  "to discover the exact size or amount of something"))
        wordArray.append(wordAndMeaning(word:"resistant", meaning:  "not wanting to accept something, especially changes or new ideas"))
        wordArray.append(wordAndMeaning(word:"suggest", meaning:  "to mention an idea, possible plan, or action for other people to consider"))
        wordArray.append(wordAndMeaning(word:"quote", meaning:  "to repeat the words that someone else has said or written"))
        wordArray.append(wordAndMeaning(word:"deny", meaning:  "to say that something is not true"))
        wordArray.append(wordAndMeaning(word:"foolish", meaning:  "unwise, stupid, or not showing good judgment"))
        wordArray.append(wordAndMeaning(word:"musterious", meaning:  "strange, not known, or not understood"))
        wordArray.append(wordAndMeaning(word:"flu", meaning:  "short for influenza"))
        wordArray.append(wordAndMeaning(word:"dislike", meaning:  "to not like someone or something"))
        wordArray.append(wordAndMeaning(word:"multiply", meaning:  "to not like someone or something"))
        wordArray.append(wordAndMeaning(word:"purple", meaning:  "of a dark reddish-blue colour"))
        wordArray.append(wordAndMeaning(word:"glimpse", meaning:  "to see something or someone for a very short time or only partly"))
        wordArray.append(wordAndMeaning(word:"stripe", meaning:  "a strip on the surface of something that is a different colour from the surrounding surface"))
        wordArray.append(wordAndMeaning(word:"visual", meaning:  "relating to seeing"))
        wordArray.append(wordAndMeaning(word:"influential", meaning:  "having a lot of influence on someone or something"))
        wordArray.append(wordAndMeaning(word:"athlete", meaning:  "a person who is very good at sports or physical exercise, especially one who competes in organized events"))
        wordArray.append(wordAndMeaning(word:"flesh", meaning:  "the soft part of the body of a person or animal that is between the skin and the bones, or the soft inside part of a fruit or vegetable"))
        wordArray.append(wordAndMeaning(word:"paste", meaning:  "a thick soft sticky substance made by mixing a liquid with a powder, especially to make a type of glue"))
        wordArray.append(wordAndMeaning(word:"immune", meaning:  "protected against a particular disease by particular substances in the blood"))
        wordArray.append(wordAndMeaning(word:"religion", meaning:  "the belief in and worship of a god or gods, or any such system of belief and worship"))
        wordArray.append(wordAndMeaning(word:"customer", meaning:  "a person who buys goods or a service"))
        wordArray.append(wordAndMeaning(word:"delay", meaning:  "to make something happen at a later time than originally planned or expected"))
        wordArray.append(wordAndMeaning(word:"inferior", meaning:  "not good, or not as good as someone or something else"))
        wordArray.append(wordAndMeaning(word:"elastic", meaning:  "An elastic material is able to stretch and be returned to its original shape or size"))
        wordArray.append(wordAndMeaning(word:"congress", meaning:  "a large formal meeting of representatives from countries or societies at which ideas are discussed and information is exchanged"))
        wordArray.append(wordAndMeaning(word:"worm", meaning:  "a small animal with a long, narrow, soft body without arms, legs, or bones"))
        wordArray.append(wordAndMeaning(word:"costly", meaning:  "expensive, especially too expensive"))
        wordArray.append(wordAndMeaning(word:"cage", meaning:  " a space surrounded on all sides by bars or wire, in which animals or birds are kept"))
        wordArray.append(wordAndMeaning(word:"jury", meaning:  "a group of people who have been chosen to listen to all the facts in a trial in a law court and to decide if a person is guilty or not guilty, or if a claim has been proved"))
        wordArray.append(wordAndMeaning(word:"salary", meaning:  "a fixed amount of money agreed every year as pay for an employee, usually paid directly into his or her bank account every month"))
        wordArray.append(wordAndMeaning(word:"chew", meaning:  "to crush food into smaller, softer pieces with the teeth so that it can be swallowed"))
        wordArray.append(wordAndMeaning(word:"selfish", meaning:  "Someone who is selfish only thinks of their own advantage"))
        wordArray.append(wordAndMeaning(word:"object", meaning:  "a thing that you can see or touch but that is not usually a living animal, plant, or person"))
        wordArray.append(wordAndMeaning(word:"velocity", meaning:  "the speed at which an object is travelling"))
        wordArray.append(wordAndMeaning(word:"salad", meaning:  "a mixture of uncooked vegetables, usually including lettuce, eaten either as a separate dish or with other food"))
        wordArray.append(wordAndMeaning(word:"regulation", meaning:  "an official rule or the act of controlling something"))
        wordArray.append(wordAndMeaning(word:"desire", meaning:  "to want something, especially strongly"))
        wordArray.append(wordAndMeaning(word:"confront", meaning:  "to face, meet, or deal with a difficult situation or person"))
        wordArray.append(wordAndMeaning(word:"eagle", meaning:  "a large, strong bird with a curved beak that eats meat and can see very well"))
        wordArray.append(wordAndMeaning(word:"garage", meaning:  "a building where a car is kept, built next to or as part of a house"))
        wordArray.append(wordAndMeaning(word:"capacity", meaning:  "the total amount that can be contained or produced, or (especially of a person or organization) the ability to do a particular thing"))
       
        wordArray.append(wordAndMeaning(word:"domestic", meaning:  "relating to a person's own country"))
        wordArray.append(wordAndMeaning(word:"guarantee", meaning:  "a promise that something will be done or will happen, especially a written promise by a company to repair or change a product that develops a fault within a particular period of time"))
        wordArray.append(wordAndMeaning(word:"mental", meaning:  "relating to the mind, or involving the process of thinking"))
        wordArray.append(wordAndMeaning(word:"suicide", meaning:  "the act of killing yourself intentionally, or a person who has done this"))
        wordArray.append(wordAndMeaning(word:"despise", meaning:  "to feel a strong dislike for someone or something because you think that that person or thing is bad or has no value"))
        wordArray.append(wordAndMeaning(word:"magnet", meaning:  "an object that is able both to attract iron and steel objects and also push them away"))
        wordArray.append(wordAndMeaning(word:"sufficient", meaning:  "enough for a particular purpose"))
        wordArray.append(wordAndMeaning(word:"layman", meaning:  "someone who is part of a religious organization but who is not paid or specially trained"))
        wordArray.append(wordAndMeaning(word:"urge", meaning:  "a strong wish, especially one that is difficult or impossible to control"))
        wordArray.append(wordAndMeaning(word:"brand", meaning:  "a type of product made by a particular company"))
        wordArray.append(wordAndMeaning(word:"specialist", meaning:  "someone who has a lot of experience, knowledge, or skill in a particular subject"))
        wordArray.append(wordAndMeaning(word:"summit", meaning:  "an important formal meeting between leaders of governments from two or more countries"))
        wordArray.append(wordAndMeaning(word:"chase", meaning:  "to hurry after someone or something in order to catch him, her, or it"))
        wordArray.append(wordAndMeaning(word:"endure", meaning:  "to suffer something difficult, unpleasant, or painful"))
        wordArray.append(wordAndMeaning(word:"sheer", meaning:  "used to emphasize how very great, important, or powerful a quality or feeling is; nothing except"))
        wordArray.append(wordAndMeaning(word:"diet", meaning:  "the food and drink usually eaten or drunk by a person or group"))
        wordArray.append(wordAndMeaning(word:"poisonous", meaning:  "very harmful and able to cause illness or death"))
        wordArray.append(wordAndMeaning(word:"engine", meaning:  "a machine that uses the energy from liquid fuel or steam to produce movement"))
        wordArray.append(wordAndMeaning(word:"sturdy", meaning:  "physically strong and solid or thick, and therefore unlikely to break or be hurt"))
        wordArray.append(wordAndMeaning(word:"response", meaning:  "an answer or reaction"))
        wordArray.append(wordAndMeaning(word:"uproar", meaning:  "a situation in which a lot of people complain about something angrily or make a lot of noise"))
        wordArray.append(wordAndMeaning(word:"stark", meaning:  "empty, simple, or obvious, especially without decoration or anything that is not necessary"))
        wordArray.append(wordAndMeaning(word:"butt", meaning:  "the part of a finished cigarette that has not been smoked"))
        wordArray.append(wordAndMeaning(word:"merciful", meaning:  "someone who is merciful is willing to be kind to and forgive people who are in their power"))
        wordArray.append(wordAndMeaning(word:"chorus", meaning:  "part of a song that is repeated several times, usually after each verse (= set of lines)"))
        wordArray.append(wordAndMeaning(word:"glossary", meaning:  "an alphabetical list, with meanings, of the words or phrases in a text that are difficult to understand"))
        wordArray.append(wordAndMeaning(word:"deduce", meaning:  "to reach an answer or a decision by thinking carefully about the known facts"))
        wordArray.append(wordAndMeaning(word:"concession", meaning:  "something that is allowed or given up, often in order to end a disagreement, or the act of allowing or giving this"))
        wordArray.append(wordAndMeaning(word:"procedure", meaning:  "a set of actions that is the official or accepted way of doing something"))
        wordArray.append(wordAndMeaning(word:"reactor", meaning:  "a large machine in which atoms are either divided or joined in order to produce power"))
        wordArray.append(wordAndMeaning(word:"brutal", meaning:  "cruel, violent, and completely without feelings"))
        wordArray.append(wordAndMeaning(word:"solemn", meaning:  "serious and without any humour"))
        wordArray.append(wordAndMeaning(word:"provoke", meaning:  "to cause a reaction, especially a negative one"))
        wordArray.append(wordAndMeaning(word:"melancholy", meaning:  "Sad"))
        wordArray.append(wordAndMeaning(word:"offset", meaning:  "to balance one influence against an opposing influence, so that there is no great difference as a result"))
        wordArray.append(wordAndMeaning(word:"strain", meaning:  " a force or influence that stretches, pulls, or puts pressure on something, sometimes causing damage"))
        wordArray.append(wordAndMeaning(word:"passive", meaning:  "not acting to influence or change a situation; allowing other people to be in control"))
        wordArray.append(wordAndMeaning(word:"thrill", meaning:  "a feeling of extreme excitement, usually caused by something pleasant"))
        wordArray.append(wordAndMeaning(word:"pave", meaning:  "to cover an area of ground with a hard, flat surface of pieces of stone, concrete, or bricks"))
        wordArray.append(wordAndMeaning(word:"cyber", meaning:  "involving, using, or relating to computers, especially the internet"))
        wordArray.append(wordAndMeaning(word:"achievement", meaning:  "something very good and difficult that you have succeeded in doing"))
        wordArray.append(wordAndMeaning(word:"annual", meaning:  "happening once every year"))
        wordArray.append(wordAndMeaning(word:"scarlet", meaning:  "bright red"))
        wordArray.append(wordAndMeaning(word:"cumulative", meaning:  "increasing by one addition after another"))
        wordArray.append(wordAndMeaning(word:"cocaine", meaning:  "a drug used in medicine to prevent pain and also used illegally, often in the form of a white powder that is breathed in through the nose"))
        wordArray.append(wordAndMeaning(word:"fraud", meaning:  "the crime of getting money by deceiving people"))
        wordArray.append(wordAndMeaning(word:"complement", meaning:  "to make something else seem better or more attractive when combining with it"))
        wordArray.append(wordAndMeaning(word:"outrage", meaning:  "a feeling of anger and shock"))
        wordArray.append(wordAndMeaning(word:"tar", meaning:  "a black substance, sticky when hot, used especially for making roads"))
        wordArray.append(wordAndMeaning(word:"cane", meaning:  "the long, hard, hollow stem of particular plants such as bamboo, sometimes used to make furniture or support other plants in the garden"))
        wordArray.append(wordAndMeaning(word:"attendance", meaning:  "the fact of going somewhere such as a church, school, etc. regularly"))
        wordArray.append(wordAndMeaning(word:"sensor", meaning:  "a device that is used to record that something is present or that there are changes in something"))
        wordArray.append(wordAndMeaning(word:"entitle", meaning:  "to give someone the right to do or have something"))
        wordArray.append(wordAndMeaning(word:"adjoin", meaning:  "to be very near, next to, or touching"))
        wordArray.append(wordAndMeaning(word:"junk", meaning:  "things that are considered to be of no use or value, or of low quality"))
        wordArray.append(wordAndMeaning(word:"cite", meaning:  "to mention something as proof for a theory or as a reason why something has happened"))
        wordArray.append(wordAndMeaning(word:"clerk", meaning:  "a person who works in an office, dealing with records or performing general office duties"))
        wordArray.append(wordAndMeaning(word:"decisive", meaning:  "able to make decisions quickly and confidently, or showing this quality"))
        wordArray.append(wordAndMeaning(word:"haul", meaning:  "to pull something heavy slowly and with difficulty"))
        wordArray.append(wordAndMeaning(word:"cannon", meaning:  "a large, powerful gun, usually attached to two or four wheels, that was used in the past to fire heavy stone or metal balls"))
        wordArray.append(wordAndMeaning(word:"crime", meaning:  "illegal activities"))
        wordArray.append(wordAndMeaning(word:"adjustable", meaning:  "able to be changed to suit particular needs"))
        wordArray.append(wordAndMeaning(word:"mast", meaning:  "a tall pole on a boat or ship that supports its sails"))
        wordArray.append(wordAndMeaning(word:"accustomed", meaning:  "familiar with something"))
        wordArray.append(wordAndMeaning(word:"flare", meaning:  "to burn brightly either for a short time or not regularly"))
        wordArray.append(wordAndMeaning(word:"detection", meaning:  "the fact of noticing or discovering something"))
        wordArray.append(wordAndMeaning(word:"tenant", meaning:  "a person who pays rent for the use of land or a building"))
        wordArray.append(wordAndMeaning(word:"initiate", meaning:  " to cause something to begin"))
        wordArray.append(wordAndMeaning(word:"reward", meaning:  "something given in exchange for good behaviour or good work, etc"))
        wordArray.append(wordAndMeaning(word:"underwear", meaning:  "clothes worn next to the skin, under other clothes"))
        wordArray.append(wordAndMeaning(word:"proof", meaning:  "a fact or piece of information that shows that something exists or is true"))
        wordArray.append(wordAndMeaning(word:"spectacle", meaning:  "an unusual or unexpected event or situation that attracts attention, interest, or disapproval"))
        wordArray.append(wordAndMeaning(word:"alternative", meaning:  "An alternative plan or method is one that you can use if you do not want to use another one"))
        wordArray.append(wordAndMeaning(word:"linear", meaning:  "consisting of or to do with lines"))
        wordArray.append(wordAndMeaning(word:"bias", meaning:  "the action of supporting or opposing a particular person or thing in an unfair way, because of allowing personal opinions to influence your judgment"))
        wordArray.append(wordAndMeaning(word:"abundance", meaning:  "the situation in which there is more than enough of something"))
        wordArray.append(wordAndMeaning(word:"banquet", meaning:  "a large formal meal for many people, often followed by speeches in honour of someone"))
        wordArray.append(wordAndMeaning(word:"devise", meaning:  "to invent a plan, system, object, etc., usually using your intelligence or imagination"))
        wordArray.append(wordAndMeaning(word:"compute", meaning:  "to calculate an answer or amount by using a machine"))
        wordArray.append(wordAndMeaning(word:"aware", meaning:  "having knowledge or perception of a situation or fact"))
        wordArray.append(wordAndMeaning(word:"awkward", meaning:  "difficult to use, do, or deal with"))
        wordArray.append(wordAndMeaning(word:"cathedral", meaning:  "a very large, usually stone, building for Christian worship. It is the largest and most important church of a diocese"))
        wordArray.append(wordAndMeaning(word:"hound", meaning:  "a type of dog used for hunting"))
        wordArray.append(wordAndMeaning(word:"audit", meaning:  "to make an official examination of the accounts of a business and produce a report"))
        wordArray.append(wordAndMeaning(word:"counter", meaning:  "a long, flat, narrow surface or table in a shop, bank, restaurant, etc. at which people are served"))
        wordArray.append(wordAndMeaning(word:"pamphlet", meaning:  "a thin book with only a few pages that gives information or an opinion about something"))
        wordArray.append(wordAndMeaning(word:"brief", meaning:  "lasting only a short time or containing few words"))
        wordArray.append(wordAndMeaning(word:"seminar", meaning:  "an occasion when a teacher or expert and a group of people meet to study and discuss something"))
        wordArray.append(wordAndMeaning(word:"sift", meaning:  "to put flour, sugar, etc. through a sieve (= wire net shaped like a bowl) to break up large pieces"))
        wordArray.append(wordAndMeaning(word:"permanence", meaning:  "staying the same or continuing for a long time"))
        wordArray.append(wordAndMeaning(word:"strife", meaning:  "violent or angry disagreement"))
        wordArray.append(wordAndMeaning(word:"prediction", meaning:  "a statement about what you think will happen in the future"))
        wordArray.append(wordAndMeaning(word:"clasp", meaning:  "to hold someone or something firmly in your hands or arms"))
        wordArray.append(wordAndMeaning(word:"persecute", meaning:  "to treat someone unfairly or cruelly over a long period of time because of their race, religion, or political beliefs, or to annoy someone by refusing to leave them alone"))
        wordArray.append(wordAndMeaning(word:"underlying", meaning:  "real but not immediately obvious"))
        wordArray.append(wordAndMeaning(word:"standardize", meaning:  "to make things of the same type all have the same basic features"))
        wordArray.append(wordAndMeaning(word:"angel", meaning:  "a spiritual being in some religions who is believed to be a messenger of God, usually represented as having a human form with wings"))
        wordArray.append(wordAndMeaning(word:"alleviate", meaning:  "to make something bad such as pain or problems less severe"))
        wordArray.append(wordAndMeaning(word:"untie", meaning:  "to unfasten a knot or something tied"))
        wordArray.append(wordAndMeaning(word:"diverse", meaning:  "including many different types of people or things"))
        wordArray.append(wordAndMeaning(word:"vow", meaning:  "to make a determined decision or promise to do something"))
        wordArray.append(wordAndMeaning(word:"tract", meaning:  "a short piece of writing, especially on a religious or political subject, that is intended to influence other people's opinions"))
        wordArray.append(wordAndMeaning(word:"bewilder", meaning:  "to confuse someone"))
        wordArray.append(wordAndMeaning(word:"synthesis", meaning:  "the production of a substance from simpler materials after a chemical reaction"))
        wordArray.append(wordAndMeaning(word:"prospect", meaning:  "the possibility that something good might happen in the future"))
        wordArray.append(wordAndMeaning(word:"loom", meaning:  "to appear as a large, often frightening or unclear shape or object"))
        wordArray.append(wordAndMeaning(word:"pastime", meaning:  "an activity that is done for enjoyment"))
        wordArray.append(wordAndMeaning(word:"manure", meaning:  "solid waste from animals, especially horses, that is spread on the land in order to make plants grow well"))
        wordArray.append(wordAndMeaning(word:"advent", meaning:  "the fact of an event happening, an invention being made, or a person arriving"))
        wordArray.append(wordAndMeaning(word:"probe", meaning:  "to try to discover information that other people do not want you to know, by asking questions carefully and not directly"))
        wordArray.append(wordAndMeaning(word:"solidify", meaning:  "to change from being a liquid or gas to a solid form, or to make something do this"))
        wordArray.append(wordAndMeaning(word:"refuge", meaning:  "(a place that gives) protection or shelter from danger, trouble, unhappiness, etc"))
        wordArray.append(wordAndMeaning(word:"decline", meaning:  "to gradually become less, worse, or lower"))
        wordArray.append(wordAndMeaning(word:"commute", meaning:  "to make the same journey regularly between work and home"))
        wordArray.append(wordAndMeaning(word:"shrink", meaning:  "to become smaller, or to make something smaller"))
        wordArray.append(wordAndMeaning(word:"denial", meaning:  "a statement that something is not true or does not exist"))
        wordArray.append(wordAndMeaning(word:"prototype", meaning:  "the first example of something, such as a machine or other industrial product, from which all later forms are developed"))
        wordArray.append(wordAndMeaning(word:"fist", meaning:  "a hand with the fingers and thumb held tightly in"))
        wordArray.append(wordAndMeaning(word:"participant", meaning:  "a person who takes part in or becomes involved in a particular activity"))
        wordArray.append(wordAndMeaning(word:"spy", meaning:  "a person who secretly collects and reports information about the activities of another country or organization"))
        wordArray.append(wordAndMeaning(word:"haughty", meaning:  "unfriendly and seeming to consider yourself better than other people"))
        wordArray.append(wordAndMeaning(word:"plea", meaning:  "an urgent and emotional request"))
        wordArray.append(wordAndMeaning(word:"recur", meaning:  "to happen many times or to happen again"))
        wordArray.append(wordAndMeaning(word:"coarse", meaning:  "rough and not smooth or soft, or not in very small pieces"))
        wordArray.append(wordAndMeaning(word:"stun", meaning:  "to shock or surprise someone very much"))
        wordArray.append(wordAndMeaning(word:"growl", meaning:  "to make a low, rough sound, usually in anger"))
        wordArray.append(wordAndMeaning(word:"recipient", meaning:  "a person who receives something"))
        wordArray.append(wordAndMeaning(word:"appeal", meaning:  "a request to the public for money, information, or help"))
        wordArray.append(wordAndMeaning(word:"gradient", meaning:  "how steep a slope is"))
        wordArray.append(wordAndMeaning(word:"myth", meaning:  "an ancient story or set of stories, especially explaining the early history of a group of people or about natural events and facts"))
        wordArray.append(wordAndMeaning(word:"charter", meaning:  "a formal statement of the rights of a country's people, or of an organization or a particular social group, that is agreed by or demanded from a ruler or government"))
        wordArray.append(wordAndMeaning(word:"ozone", meaning:  "a poisonous form of oxygen"))
        wordArray.append(wordAndMeaning(word:"treatly", meaning:  "a written agreement between two or more countries, formally approved and signed by their leaders"))
        wordArray.append(wordAndMeaning(word:"pinpoint", meaning:  "to find out or say the exact position in space or time of something"))
        wordArray.append(wordAndMeaning(word:"retort", meaning:  "to answer someone quickly in an angry or funny way"))
        wordArray.append(wordAndMeaning(word:"gloomy", meaning:  "unhappy and without hope"))
        wordArray.append(wordAndMeaning(word:"lane", meaning:  "a narrow road in the countryside or in a town"))
        wordArray.append(wordAndMeaning(word:"scale", meaning:  "a set of numbers, amounts, etc., used to measure or compare the level of something"))
        wordArray.append(wordAndMeaning(word:"prose", meaning:  "written language in its ordinary form rather than poetry"))
        wordArray.append(wordAndMeaning(word:"retain", meaning:  "to keep or continue to have something"))
        wordArray.append(wordAndMeaning(word:"stability", meaning:  "a situation in which something is not likely to move or change"))
        wordArray.append(wordAndMeaning(word:"notation", meaning:  "a system of written symbols used especially in mathematics or to represent musical notes"))
        wordArray.append(wordAndMeaning(word:"coherent", meaning:  "If an argument, set of ideas, or a plan is coherent, it is clear and carefully considered, and each part of it connects or follows in a natural or reasonable way"))
        wordArray.append(wordAndMeaning(word:"bribe", meaning:  "to try to make someone do something for you by giving them money, presents, or something else that they want"))
        wordArray.append(wordAndMeaning(word:"rank", meaning:  "a position in an organization, such as the army, showing the importance of the person having it"))
        wordArray.append(wordAndMeaning(word:"immigrant", meaning:  "a person who has come to a different country in order to live there permanently"))
        wordArray.append(wordAndMeaning(word:"external", meaning:  "of, on, for, or coming from the outside"))
        wordArray.append(wordAndMeaning(word:"float", meaning:  "to stay on the surface of a liquid and not sink"))
        wordArray.append(wordAndMeaning(word:"grove", meaning:  "a group of trees planted close together"))
        wordArray.append(wordAndMeaning(word:"occupation", meaning:  "a person's job"))
        wordArray.append(wordAndMeaning(word:"impurity", meaning:  "the fact that a substance is dirty or lower in quality because it is mixed with another substance, or something that causes this"))
        wordArray.append(wordAndMeaning(word:"ruin", meaning:  "to spoil or destroy something completely"))
        wordArray.append(wordAndMeaning(word:"extinguish", meaning:  "to stop a fire or a light burning"))
        wordArray.append(wordAndMeaning(word:"exert", meaning:  "to use something such as authority, power, influence, etc. in order to make something happen"))
        wordArray.append(wordAndMeaning(word:"successive", meaning:  "happening one after the other without any break"))
        wordArray.append(wordAndMeaning(word:"marvel", meaning:  "to show or experience great surprise or admiration"))
        wordArray.append(wordAndMeaning(word:"extensive", meaning:  "covering a large area; having a great range"))
        wordArray.append(wordAndMeaning(word:"cancel", meaning:  "to decide that an organized event will not happen, or to stop an order for goods or services that you no longer want"))
        wordArray.append(wordAndMeaning(word:"poetry", meaning:  "poems in general as a form of literature"))
        wordArray.append(wordAndMeaning(word:"fracture", meaning:  "If something hard, such as a bone, fractures, or is fractured, it breaks or cracks"))
        wordArray.append(wordAndMeaning(word:"forum", meaning:  "a situation or meeting in which people can talk about a problem or matter especially of public interest"))
        wordArray.append(wordAndMeaning(word:"multiply", meaning:  "to increase very much in number, or (in mathematics) to add a number to itself a particular number of times"))
        wordArray.append(wordAndMeaning(word:"batch", meaning:  "a group of things or people dealt with at the same time or considered similar in type"))
        wordArray.append(wordAndMeaning(word:"precedent", meaning:  "an action, situation, or decision that has already happened and can be used as a reason why a similar action or decision should be performed or made"))
        wordArray.append(wordAndMeaning(word:"stylish", meaning:  "of a high quality in appearance, design, or behaviour"))
        wordArray.append(wordAndMeaning(word:"deceptive", meaning:  "making you believe something that is not true"))
        wordArray.append(wordAndMeaning(word:"outward", meaning:  "relating to how people, situations, or things seem to be, rather than how they are inside"))
        wordArray.append(wordAndMeaning(word:"segment", meaning:  "one of the smaller groups or amounts that a larger group or amount can be divided into"))
        wordArray.append(wordAndMeaning(word:"reunion", meaning:  "a social event for a group of people who have not seen each other for a long time"))
        wordArray.append(wordAndMeaning(word:"afflict", meaning:  "If a problem or illness afflicts a person or thing, they suffer from it"))
        wordArray.append(wordAndMeaning(word:"knob", meaning:  "a round handle, or a small, round device for controlling a machine or electrical equipment"))
        wordArray.append(wordAndMeaning(word:"cereal", meaning:  "a plant that is grown to produce grain"))
        wordArray.append(wordAndMeaning(word:"discourse", meaning:  "communication in speech or writing"))
        wordArray.append(wordAndMeaning(word:"retail", meaning:  "the activity of selling goods to the public, usually in shops"))
        wordArray.append(wordAndMeaning(word:"slum", meaning:  "a very poor and crowded area, especially of a city"))
        wordArray.append(wordAndMeaning(word:"kit", meaning:  "a set of things, such as tools or clothes, used for a particular purpose or activity"))
        wordArray.append(wordAndMeaning(word:"plateau", meaning:  "a large flat area of land that is high above sea level"))
        wordArray.append(wordAndMeaning(word:"considerate", meaning:  "kind and helpful"))
        wordArray.append(wordAndMeaning(word:"regime", meaning:  "a particular government or a system or method of government"))
        wordArray.append(wordAndMeaning(word:"erupt", meaning:  "When a volcano erupts, it explodes and flames and rocks come out of it"))
        wordArray.append(wordAndMeaning(word:"obsolete", meaning:  "not in use anymore, having been replaced by something newer and better or more fashionable"))
        wordArray.append(wordAndMeaning(word:"shrub", meaning:  "a large plant with a rounded shape formed from many small branches growing either directly from the ground or from a hard stem, grown in gardens"))
        wordArray.append(wordAndMeaning(word:"ventilate", meaning:  "to cause fresh air to enter and move around a closed space"))
        wordArray.append(wordAndMeaning(word:"discard", meaning:  "to throw something away or get rid of it because you no longer want or need it"))
        wordArray.append(wordAndMeaning(word:"crank", meaning:  "a person who has strange or unusual ideas and beliefs"))
        wordArray.append(wordAndMeaning(word:"soluble", meaning:  "able to be dissolved to form a solution"))
        wordArray.append(wordAndMeaning(word:"cycle", meaning:  "a bicycle"))
        wordArray.append(wordAndMeaning(word:"stew", meaning:  "a type of food consisting usually of meat or fish and vegetables cooked slowly in a small amount of liquid"))
        wordArray.append(wordAndMeaning(word:"classic", meaning:  "having a high quality or standard against which other things are judged"))
        wordArray.append(wordAndMeaning(word:"muddy", meaning:  "covered by or containing mud (= wet, sticky earth)"))
        wordArray.append(wordAndMeaning(word:"leisure", meaning:  "the time when you are not working or doing other duties"))
        wordArray.append(wordAndMeaning(word:"faction", meaning:  "a group within a larger group, especially one with slightly different ideas from the main group"))
        wordArray.append(wordAndMeaning(word:"pier", meaning:  "a low structure built at the edge of water, used especially for getting into and out of boats"))
        wordArray.append(wordAndMeaning(word:"cling", meaning:  "to stick onto or hold something or someone tightly, or to refuse to stop holding it, him, or her"))
        wordArray.append(wordAndMeaning(word:"exotic", meaning:  "unusual and exciting because of coming (or seeming to come) from far away, especially a tropical country"))
        wordArray.append(wordAndMeaning(word:"cabinet", meaning:  "a small group of the most important people in government, who advise the President or Prime Minister and make important decisions"))
        wordArray.append(wordAndMeaning(word:"oath", meaning:  "a promise, especially that you will tell the truth in a law court"))
        wordArray.append(wordAndMeaning(word:"collapse", meaning:  "to fall down suddenly because of pressure or having no strength or support"))
        wordArray.append(wordAndMeaning(word:"overflow", meaning:  "When a liquid overflows, it flows over the edges of a container, etc. because there is too much of it"))
        wordArray.append(wordAndMeaning(word:"fantastic", meaning:  "extraordinarily good or attractive"))

        //This will help users to filter words
        currentWordArray=wordArray
    }
    //This code will add words and explanations into word array
    
    
    private func setUpSearchBar() {
        searchBar.delegate = self
    }

    
    
    func alterLayout() {
        tabel.tableHeaderView=UIView()
        tabel.estimatedSectionHeaderHeight = 100
        navigationItem.leftBarButtonItem=UIBarButtonItem(customView: searchBar)
        searchBar.showsScopeBar = false
    }
    //This will set the basic look of table view

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return currentWordArray.count
    }
    //This code will make the number of sections of tableView depend on the number of words in currentWordArray
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    guard let cell = tableView.dequeueReusableCell(withIdentifier: "Cell") as? TableCell else {
            return UITableViewCell()
        }
    cell.wordLbl.text=currentWordArray[indexPath.row].word
        cell.meaningLbl.text=currentWordArray[indexPath.row].meaning
        return cell
    }
    //This function will make word label to show the word in currentWordArray and meaning label to show the meaning in the currentWordArray
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 120
    }
    //This function will set the height of the indexpath
    
   func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        return searchBar
    }
    //This function will make the searchBar at the top of viewController
    
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
       return UITableViewAutomaticDimension
   }
    //This will set the height for header in section automatically
    
    
    //search bar
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        guard !searchText.isEmpty else {
            currentWordArray = wordArray
            tabel.reloadData()
            return}
        currentWordArray=wordArray.filter({word -> Bool in
           word.word.lowercased().contains(searchText.lowercased())
        })
        tabel.reloadData()
    }
    //if there is something in the search bar, this function will pass the words in the wordArray to the currentWordArray and the tableView will show all possibilities no matter lowercase or capital.
    func searchBar(_ searchBar: UISearchBar, selectedScopeButtonIndexDidChange selectedScope: Int){
        
    }
}
class wordAndMeaning {
    let word:String
    let meaning:String
    
    init(word:String, meaning: String) {
        self.word=word
        self.meaning=meaning
    }
}
//This class will help people to put words into this app.




